#!/usr/bin/env python

import os
import sys
import random
from math import *
from datetime import datetime

def w(z): sys.stdout.write(z)

def gen(ranks, x):
    d = datetime.now()
    random.seed(os.getpid() * d.microsecond * d.second)
    for i in xrange(0, 1000): ranks[random.randint(0, 9)] += 1.
    for i in xrange(0, 10):   x += ((ranks[i] - 100) ** 2) / 100.
    return x

if __name__ == '__main__':
    p = map(float, [100, 90, 80, 70, 50, 30, 20, 10, 5, 2, 1, 0])
    x2 = map(float, [0, 4.128, 5.480, 6.393, 8.343, 10.656, 12.242, 14.684, 16.919, 19.679, 21.666, 1000])
    ranks = map(int, [0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
    x = gen(ranks, 0.)
    w("\t  x   Ox\n")
    for i in xrange(0, 10): w("\t%3d  %3d\n" % (i, ranks[i]))
    for i in xrange(0, 11):
        if x >= x2[i] and x <= x2[i + 1]:
            w("%g <= X2 <= %g\n" % (x2[i], x2[i + 1]))
            w("%.3f <= P <= %.3f\n" % (p[i + 1] * 0.01, p[i] * 0.01))
            break
    w("X2 = %f\n" % x)
