##
## Makefile for  in /home/wotan/project/Epikong
## 
## Made by geoffroy aubey
## Login   <aubey_g@epitech.net>
## 
## Started on  Sat Mar  3 00:15:22 2012 geoffroy aubey
## Last update Sat Mar  3 00:15:22 2012 geoffroy aubey
##

all:
		make  -C ./etape_1
		make  -C ./etape_2
		make  -C ./etape_3
		make  -C ./etape_4

clean:
		make clean -C ./etape_1
		make clean -C ./etape_2
		make clean -C ./etape_3
		make clean -C ./etape_4

fclean: 	clean
		make fclean -C ./etape_1
		make fclean -C ./etape_2
		make fclean -C ./etape_3
		make fclean -C ./etape_4

re:		fclean all
